# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0002_auto_20170819_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultedPhoto',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('small_photo', models.ImageField(blank=True, null=True, upload_to='photo_directory_path_s', verbose_name='Small Image')),
                ('large_photo', models.ImageField(blank=True, null=True, upload_to='photo_directory_path_l', verbose_name='large Image')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.CECBRProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
