# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 02:43
from __future__ import unicode_literals

import cecbr.photos.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_squashed_0005_auto_20170816_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('album_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=128)),
                ('album_date', models.DateField()),
                ('count', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('analyzed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Albums',
                'verbose_name': 'Album',
                'ordering': ['season', '-album_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128)),
                ('trained', models.BooleanField(default=False)),
                ('trained_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(to='photos.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('small_url', models.URLField()),
                ('large_url', models.URLField()),
                ('face_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('people_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('analyzed_date', models.DateTimeField(blank=True, null=True)),
                ('identified', models.BooleanField(default=False)),
                ('identified_date', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photo',
                'ordering': ['album', 'photo_id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('season_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Seasons',
                'verbose_name': 'Season',
                'ordering': ['-season_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=cecbr.photos.models.training_directory_path)),
                ('face_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cecbrprofile',
            options={'verbose_name': 'CECBR Profile', 'verbose_name_plural': 'CECBR Profiles'},
        ),
        migrations.AddField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.CECBRProfile'),
        ),
        migrations.AddField(
            model_name='album',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Season'),
        ),
    ]
