# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170819_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='analyzed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
