# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_group_analyzed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(default='http://foo.com'),
            preserve_default=False,
        ),
    ]
