# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_album_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='face_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='people_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingphoto',
            name='face_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
