# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_cecbrprofile__cecbr_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecbrprofile',
            name='last_album_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
