# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0005_auto_20170820_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer', models.FileField(blank=True, upload_to='')),
                ('trained', models.BooleanField(default=False)),
                ('trained_date', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisPhoto',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('raw_photo', models.ImageField(upload_to='')),
                ('detected_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('detected', models.BooleanField(default=False)),
                ('detected_date', models.DateTimeField(blank=True, null=True)),
                ('faced', models.BooleanField(default=False)),
                ('faced_date', models.DateTimeField(blank=True, null=True)),
                ('group', models.ManyToManyField(to='photoanalysis.AnalysisGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
